application.title=delta-me13
application.version=1.0.0

spring.application.name=delta-me13
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.instance-id=${spring.application.name}:${spring.cloud.client.hostname}:${server.port}:${random.value}

spring.neo4j.uri=${SPRING_DATA_NEO4J_URI:bolt://neo4j-orexis:7687}
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=frozenapp12
spring.data.neo4j.database=neo4j

spring.data.mongodb.database=hsrdbmongo
spring.data.mongodb.port=27017
spring.data.mongodb.host=${SPRING_DATA_MONGODB_HOST:mongo-orexis}
spring.data.mongodb.auto-index-creation=true

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis-orexis}
spring.data.redis.port=6379

server.error.include-message=always

spring.autoconfigure.exclude=org.springframework.boot.actuate.autoconfigure.logging.OpenTelemetryLoggingAutoConfiguration

management.endpoints.web.exposure.include=health,info,logfile,metrics
management.endpoint.logfile.enabled=true
logging.file.name=/app/logs/${spring.application.name}.log
spring.output.ansi.enabled=ALWAYS

# Must match Aquila's application.security.gateway-signing-secret
application.security.gateway-signing-secret=+R2TRnIxwru14yuPWvKM29LXxMKSsYaemu4j+jYsdMg=

scheduler.celestia.checkForUpdate=true
celestia.data.refresh-cron=0 0 3 */3 * ?


